### ISSUE TITLE
inclusion of functions in ReLTER

### ISSUE THREAD

**Issue by oggioniale** [micha-silver/MODIS-download#1]
Dear @micha-silver,
it would be interesting to be able to include these functions in the ReLTER package.
What do you think?

**Comment by micha-silver** [comment]
Hi @Ale:
(Sorry for the slow response)
FIrst, regarding a stable version on CRAN, you know the FOSS saying: "Release early, release often".  So if you feel it's ready, go ahead. 

However I do think that there are plenty of improvements that could be added fairly quickly. For example, I think that I could have those suggestions that I mentioned ready in a few weeks, Most are already written, more or less, in that demo that I did a year ago for cropping CORINE and MODIS images. And my additional idea of merging all your `getSite*()` functions into one, with an addition parameter "category" to choose what category of information to get from DEIMS could also be implemented easily: the existing functions are all mostly identical, so one generic one could be written from the existing code. 
If you agree with these ideas, I can go ahead and put something into the `dev` branch for testing...

**Comment by oggioniale** [comment]
Hi @micha-silver,
I agree about the the saying FOSS!
However, I implemented the get_site_info with category. I need to finish the test and after I can deliver in dev branch.
About aspect about CORINE and MODIS, I agree please go ahead.
Ale

**Comment by micha-silver** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    
    
    On 03/11/2021 09:51, Alessandro Oggioni
      wrote:
    
    
      
      Hi @micha-silver,
        I agree about the the saying FOSS!
        However, I implemented the get_site_info with category. I need
        to finish the test and after I can deliver in dev branch.
      
    
    Terrific!
    
      
        About aspect about CORINE and MODIS, I agree please go ahead.
      
    
    OK, I'm on it. :-)
    
    
    
      
        Ale
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/micha-silver/MODIS-download/issues/1#issuecomment-958718522",
"url": "https://github.com/micha-silver/MODIS-download/issues/1#issuecomment-958718522",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Micha Silver
Ben Gurion Univ.
Sde Boker, Remote Sensing Lab
cell: +972-523-665918
https://orcid.org/0000-0002-1128-1325
